auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki  # Define o diretório base para armazenamento
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index  # Local do índice ativo
    cache_location: /loki/cache         # Local do cache

limits_config:
  allow_structured_metadata: false

compactor:
  working_directory: /loki/compactor

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
