services:

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "14317:4317"
      - "14318:4318"
      - "19464:9464"
    depends_on:
      - jaeger
      - prometheus
      - loki
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  
      - "4317:4317"   
      - "4318:4318"
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/prometheus/config.yaml"]
    volumes:
      - ./prometheus/config.yaml:/prometheus/config.yaml
    ports:
      - 9090:9090
      

  grafana:
    image: grafana/grafana
    ports:
      - 3400:3000
    depends_on:
      - prometheus
      - loki
      - jaeger
      - otel

  loki:
    image: grafana/loki:3.4.2
    ports:
      - 3100:3100
      - 9096:9096
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:latest
    ports:
    - "3200:3200"  # HTTP e gRPC
    command: [
      "-config.file=/etc/tempo-local.yaml"
    ]
    volumes:
      - ./tempo/config.yaml:/etc/tempo-local.yaml

  

