apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-prometheus:9090
    isDefault: true
    uid: prometheus
    basicAuth: true
    basicAuthUser: otel
    secureJsonData:
      basicAuthPassword: observability123
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://otel-loki:3100
    uid: loki
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://otel-jaeger:16686
    uid: jaeger
    editable: false

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://otel-alertmanager:9093
    uid: alertmanager
    jsonData:
      implementation: prometheus
    editable: false
