
FROM ruby:3.3.6-slim AS base

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install

COPY . .

FROM base AS development

ENV RAILS_ENV=development
