global:
  scrape_interval: 5s  # Define a frequência de coleta das métricas

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]  # Pegando métricas do OpenTelemetry Collector
