server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 5m
  max_block_bytes: 104857600

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
